max_cores:  12
star_ulimit: 64000 ## 4096 or thereabouts is system default, 64000 helps, higher may not work due to hard limits set by the OS
star_load: 90
star_extra_param: "" ## leave blank for normal read lengths >75bp $ --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outFilterMatchNmin 0 --outFilterMismatchNmax 2
star_fix_shortread_issues: "no" # ONLY use this for datasets with VERY short reads like the mnseq
l1em_max_cores: 12 # this still needs to be read by l1em, rn this parameter is used by multiple tools

high_intensity_rules_load: 85
mid_intensity_rules_load: 45 ##
low_intensity_rules_load: 15

aria3c_parallel_downloads: 32 # default 4, range 1 to 32. Usage: how many parallel connections do we allow during the fastq.gz download from EBI?

pre_process_pair_or_single_end: "paired" ## single or paired
pre_process_down_sample_rate: 0.1 ## 1 means no downsampling
pre_process_disk_space_experimental: "no"
phred_score: 25

#transposon_mode: "yes"
transposon_species: "elegans" ## this is for classic tetranscript and L1EM, [rat mouse elegans or human]


transposon_read_cutoff: 20 # for telocal among others, this is rowsums so n=10 is still a bit low, do further corrections downstream
transposon_star_outFilterMultimapNmax: 100
transposon_star_winAnchorMultimapNmax: 100
transposon_stranded: "no" # for tet tools and TELocal [no, forward, reverse], NB: Illumina TruSeq stranded is reverse


l1em_species: "" ## _mm39 for mouse and blank for human
l1em_stranded: "_unstranded" ## leave blank for stranded and add "_unstranded" if needed
l1em_min_reads: 5
l1em_min_fold_enrich: 4
#l1em_path: "data/L1EM-master"


#### ARTDECO
artdeco_type: "PE" # SE or PE
artdeco_stranded: "False" # False or True
artdeco_stranded_htseq: "no" # yes, no, reverse, NB: Illumina TruSeq stranded is reverse
artdeco_readthru_dist: 1 # default is 10kb so 10000
artdeco_readin_dist: 1 # default is 1kb so 1000
intergenic_max_len: 10000 # default is 15kb so 15000, default I use for mammals is 2500
featurecounts_fracOverlap: 0.95 ## default is 0

## experimental, do an artdeco run for each interval
artdeco_readthru_intervals: ["0-10", "10-20", "20-30", "30-40", "40-50", "50-60", "60-70", "70-80", "80-90", "90-100"] ## left one is artdeco_readthru_dist and right one is intergenic_max_len
artdeco_readthru_intervals_default: ["0-10"]
artdeco_readin_intervals_default: ["0-10"]


