## renames the gtf generated by bed2gtf so it is compatible with htseq
print("running rename_gtf_for_artdeco.R")

args = commandArgs(trailingOnly=TRUE)
gtf_path <- args[1]
bed_path <- args[2]

print("A")

rt <- read.csv(gtf_path, sep = "\t", header = F)
bed <- read.csv(bed_path, sep = "\t", header = F)
print("b")

print(head(bed))
print(head(rt))
rt$V3 <- "exon"

print(dim(rt)[1])
print(dim(bed)[1])

if(dim(rt)[1] != dim(bed)[1]){
  print("error healthcheck failed! GTF and bed mismatched lengths")
  return("error healthcheck failed! GTF and bed mismatched lengths")
}
print("C")
rt$V9 <- paste('gene_id "', bed$V4,'";', sep = "")

print(
  paste0(dirname(gtf_path), "/renamed_",basename(gtf_path))
  
)
write.table(rt,paste0(dirname(gtf_path), "/renamed_",basename(gtf_path)), sep = "\t", row.names = F, quote = F, col.names = F)